"""Added contact_info column to patients table

Revision ID: c09153654124
Revises: 
Create Date: 2024-12-17 20:18:23.521245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c09153654124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('surgery', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('medicines', sa.Text(), nullable=True))
        batch_op.drop_column('id')
        batch_op.drop_column('treatment')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.String(length=255), nullable=True))
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('email')
        batch_op.drop_column('email')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.alter_column('address',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('contact_info')

    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('medicines')
        batch_op.drop_column('surgery')
        batch_op.drop_column('history_id')

    op.create_table('appointments',
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('appointment_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name='appointments_ibfk_1'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
